name: DeepIsaHOL
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - brotli=1.2.0=h7d5ae5b_1
  - brotli-bin=1.2.0=hc919400_1
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - contourpy=1.3.3=py311h5a5e7c7_3
  - cycler=0.12.1=pyhcf101f3_2
  - fonttools=4.61.0=py311ha9b3269_0
  - freetype=2.14.1=hce30654_0
  - kiwisolver=1.4.9=py311h26d6576_2
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libblas=3.11.0=4_h51639a9_openblas
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=4_hb0561ab_openblas
  - libcxx=21.1.7=hf598326_0
  - libdeflate=1.25=hc11a715_0
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=4_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libopenblas=0.3.30=openmp_ha158390_3
  - libpng=1.6.53=hfab5511_0
  - libsqlite=3.51.1=h9a5124b_0
  - libtiff=4.7.1=h4030677_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.7=h4a912ad_0
  - matplotlib=3.10.8=py311ha1ab1f8_0
  - matplotlib-base=3.10.8=py311h29553df_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - numpy=2.3.5=py311h8685306_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pillow=12.0.0=py311hb52a7e5_2
  - pip=25.3=pyh8b19718_0
  - pthread-stubs=0.4=hd74edd7_1002
  - py4j=0.10.9.9=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - python=3.11.14=h18782d2_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=8_cp311
  - qhull=2020.2=h420ef59_5
  - readline=8.2=h1d1bf99_2
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - tk=8.6.13=h892fb3f_3
  - tornado=6.5.2=py311h9408147_2
  - tzdata=2025b=h78e105d_0
  - unicodedata2=17.0.0=py311h9408147_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - zlib-ng=2.3.2=h248ca61_0
  - zstd=1.5.7=hbf9d68e_6
  - pip:
    - Jinja2==3.1.4
    - Markdown==3.8.2
    - MarkupSafe==2.1.5
    - PyYAML==6.0.2
    - Pygments==2.19.2
    - Werkzeug==3.1.3
    - absl-py==2.3.1
    - accelerate==1.9.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.15
    - aiosignal==1.4.0
    - annotated-types==0.7.0
    - anyio==4.12.0
    - attrs==25.3.0
    - certifi==2025.8.3
    - charset-normalizer==3.4.2
    - cut-cross-entropy==25.1.1
    - datasets==3.6.0
    - dill==0.3.8
    - docstring_parser==0.17.0
    - filelock==3.13.1
    - frozenlist==1.7.0
    - fsspec==2024.6.1
    - gguf==0.17.1
    - grpcio==1.74.0
    - h11==0.16.0
    - hf-xet==1.1.5
    - hf_transfer==0.1.9
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.34.3
    - idna==3.10
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.4.1
    - markdown-it-py==3.0.0
    - mdurl==0.1.2
    - mistral_common==1.8.4
    - mpmath==1.3.0
    - msgspec==0.19.0
    - multidict==6.6.3
    - multiprocess==0.70.16
    - networkx==3.3
    - ollama==0.5.1
    - pandas==2.3.1
    - peft==0.17.0
    - propcache==0.3.2
    - protobuf==6.31.1
    - psutil==7.0.0
    - pyarrow==21.0.0
    - pycountry==24.6.1
    - pydantic==2.11.7
    - pydantic-extra-types==2.10.5
    - pydantic_core==2.33.2
    - pytz==2025.2
    - referencing==0.36.2
    - regex==2025.7.34
    - requests==2.32.4
    - rich==14.1.0
    - rpds-py==0.27.1
    - safetensors==0.5.3
    - sentencepiece==0.2.0
    - shtab==1.7.2
    - sympy==1.13.3
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - tiktoken==0.11.0
    - timm==1.0.19
    - tokenizers==0.21.4
    - torch==2.7.1
    - torchaudio==2.7.1
    - torchvision==0.22.1
    - tqdm==4.67.1
    - transformers==4.54.1
    - trl==0.20.0
    - typeguard==4.4.4
    - typing-inspection==0.4.1
    - typing_extensions==4.14.1
    - tyro==0.9.27
    - tzdata==2025.2
    - urllib3==2.5.0
    - xformers==0.0.31.post1
    - xxhash==3.5.0
    - yarl==1.20.1

prefix: "/Users/jonathan/.local/share/mamba/envs/DeepIsaHOL"
